name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint_and_typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    env:
      PYTHONPATH: ${{ github.workspace }}/fragua

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # --- Cache pip dependencies ---
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mypy pylint black

      # --- Black (format checking only) ---
      - name: Check code formatting with Black
        run: |
          black --check .

      # --- Pylint ---
      - name: Lint with pylint
        run: |
          pylint \
            --output-format=colorized \
            --extension-pkg-whitelist=pydantic \
            --disable=C0103 \
            fragua/agents \
            fragua/core \
            fragua/utils \
            fragua/store \
            fragua/styles \
            fragua/params \
            fragua/core/base_params.py --disable=R0903

      # --- Mypy ---
      - name: Type checking with mypy
        run: |
          mypy \
            --strict \
            --pretty \
            --ignore-missing-imports \
            --disallow-untyped-defs \
            --python-version 3.10 \
            fragua/agents \
            fragua/core \
            fragua/utils \
            fragua/store \
            fragua/styles \
            fragua/params
